{
 "cells": [
  {
   "cell_type": "code",
   "execution_count": 7,
   "metadata": {},
   "outputs": [
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "Error fetching and storing trades for joe: ('Connection aborted.', ConnectionResetError(10054, 'An existing connection was forcibly closed by the remote host', None, 10054, None))\n",
      "Error fetching and storing trades for sxp: ('Connection aborted.', ConnectionResetError(10054, 'An existing connection was forcibly closed by the remote host', None, 10054, None))\n",
      "Error fetching and storing trades for sxp: ('Connection aborted.', ConnectionResetError(10054, 'An existing connection was forcibly closed by the remote host', None, 10054, None))\n",
      "Error fetching and storing trades for blz: ('Connection aborted.', ConnectionResetError(10054, 'An existing connection was forcibly closed by the remote host', None, 10054, None))\n",
      "Error fetching and storing trades for perl: ('Connection aborted.', ConnectionResetError(10054, 'An existing connection was forcibly closed by the remote host', None, 10054, None))\n",
      "Error fetching and storing trades for joe: ('Connection aborted.', ConnectionResetError(10054, 'An existing connection was forcibly closed by the remote host', None, 10054, None))\n",
      "Error fetching and storing trades for perl: ('Connection aborted.', ConnectionResetError(10054, 'An existing connection was forcibly closed by the remote host', None, 10054, None))\n"
     ]
    },
    {
     "name": "stderr",
     "output_type": "stream",
     "text": [
      "Exception in thread Thread-13:\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Users\\Ask78\\AppData\\Local\\Temp\\ipykernel_19556\\3918153311.py\", line 46, in fetch_and_store_recent_trades\n",
      "  File \"C:\\Users\\Ask78\\AppData\\Local\\Temp\\ipykernel_19556\\2436743614.py\", line 17, in get_db_connection\n",
      "  File \"c:\\Users\\Ask78\\anaconda3\\envs\\bapi\\lib\\site-packages\\psycopg2\\__init__.py\", line 122, in connect\n",
      "    conn = _connect(dsn, connection_factory=connection_factory, **kwasync)\n",
      "psycopg2.OperationalError: could not translate host name \"ahsanpost.postgres.database.azure.com\" to address: Unknown host\n",
      "\n",
      "\n",
      "During handling of the above exception, another exception occurred:\n",
      "\n",
      "Traceback (most recent call last):\n",
      "  File \"c:\\Users\\Ask78\\anaconda3\\envs\\bapi\\lib\\threading.py\", line 932, in _bootstrap_inner\n",
      "    self.run()\n",
      "  File \"c:\\Users\\Ask78\\anaconda3\\envs\\bapi\\lib\\threading.py\", line 870, in run\n",
      "    self._target(*self._args, **self._kwargs)\n",
      "  File \"C:\\Users\\Ask78\\AppData\\Local\\Temp\\ipykernel_19556\\3918153311.py\", line 57, in fetch_and_store_recent_trades\n",
      "psycopg2.InterfaceError: connection already closed\n",
      "Exception in thread Thread-21:\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Users\\Ask78\\AppData\\Local\\Temp\\ipykernel_19556\\3918153311.py\", line 46, in fetch_and_store_recent_trades\n",
      "  File \"C:\\Users\\Ask78\\AppData\\Local\\Temp\\ipykernel_19556\\2436743614.py\", line 17, in get_db_connection\n",
      "  File \"c:\\Users\\Ask78\\anaconda3\\envs\\bapi\\lib\\site-packages\\psycopg2\\__init__.py\", line 122, in connect\n",
      "    conn = _connect(dsn, connection_factory=connection_factory, **kwasync)\n",
      "psycopg2.OperationalError: could not translate host name \"ahsanpost.postgres.database.azure.com\" to address: Unknown host\n",
      "\n",
      "\n",
      "During handling of the above exception, another exception occurred:\n",
      "\n",
      "Traceback (most recent call last):\n",
      "  File \"c:\\Users\\Ask78\\anaconda3\\envs\\bapi\\lib\\threading.py\", line 932, in _bootstrap_inner\n",
      "    self.run()\n",
      "  File \"c:\\Users\\Ask78\\anaconda3\\envs\\bapi\\lib\\threading.py\", line 870, in run\n",
      "    self._target(*self._args, **self._kwargs)\n",
      "  File \"C:\\Users\\Ask78\\AppData\\Local\\Temp\\ipykernel_19556\\3918153311.py\", line 57, in fetch_and_store_recent_trades\n",
      "psycopg2.InterfaceError: connection already closed\n"
     ]
    },
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "Error fetching and storing trades for perl: could not translate host name \"ahsanpost.postgres.database.azure.com\" to address: Unknown host\n",
      "\n",
      "Error fetching and storing trades for joe: could not translate host name \"ahsanpost.postgres.database.azure.com\" to address: Unknown host\n",
      "\n",
      "Error fetching and storing trades for chess: could not translate host name \"ahsanpost.postgres.database.azure.com\" to address: Unknown host\n",
      "\n"
     ]
    },
    {
     "name": "stderr",
     "output_type": "stream",
     "text": [
      "Exception in thread Thread-27:\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Users\\Ask78\\AppData\\Local\\Temp\\ipykernel_19556\\2436743614.py\", line 46, in fetch_and_store_recent_trades\n",
      "  File \"C:\\Users\\Ask78\\AppData\\Local\\Temp\\ipykernel_19556\\2436743614.py\", line 17, in get_db_connection\n",
      "  File \"c:\\Users\\Ask78\\anaconda3\\envs\\bapi\\lib\\site-packages\\psycopg2\\__init__.py\", line 122, in connect\n",
      "    conn = _connect(dsn, connection_factory=connection_factory, **kwasync)\n",
      "psycopg2.OperationalError: could not translate host name \"ahsanpost.postgres.database.azure.com\" to address: Unknown host\n",
      "\n",
      "\n",
      "During handling of the above exception, another exception occurred:\n",
      "\n",
      "Traceback (most recent call last):\n",
      "  File \"c:\\Users\\Ask78\\anaconda3\\envs\\bapi\\lib\\threading.py\", line 932, in _bootstrap_inner\n",
      "    self.run()\n",
      "  File \"c:\\Users\\Ask78\\anaconda3\\envs\\bapi\\lib\\threading.py\", line 870, in run\n",
      "    self._target(*self._args, **self._kwargs)\n",
      "  File \"C:\\Users\\Ask78\\AppData\\Local\\Temp\\ipykernel_19556\\2436743614.py\", line 57, in fetch_and_store_recent_trades\n",
      "psycopg2.InterfaceError: connection already closed\n"
     ]
    },
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "Error fetching and storing trades for perl: ('Connection aborted.', ConnectionResetError(10054, 'An existing connection was forcibly closed by the remote host', None, 10054, None))\n",
      "Error fetching and storing trades for perl: ('Connection aborted.', ConnectionResetError(10054, 'An existing connection was forcibly closed by the remote host', None, 10054, None))\n",
      "Error fetching and storing trades for blz: HTTPSConnectionPool(host='api.binance.com', port=443): Read timed out. (read timeout=10)\n"
     ]
    },
    {
     "name": "stderr",
     "output_type": "stream",
     "text": [
      "Exception in thread Thread-31:\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Users\\Ask78\\AppData\\Local\\Temp\\ipykernel_19556\\2436743614.py\", line 46, in fetch_and_store_recent_trades\n",
      "  File \"C:\\Users\\Ask78\\AppData\\Local\\Temp\\ipykernel_19556\\2436743614.py\", line 17, in get_db_connection\n",
      "  File \"c:\\Users\\Ask78\\anaconda3\\envs\\bapi\\lib\\site-packages\\psycopg2\\__init__.py\", line 122, in connect\n",
      "    conn = _connect(dsn, connection_factory=connection_factory, **kwasync)\n",
      "psycopg2.OperationalError: connection to server at \"ahsanpost.postgres.database.azure.com\" (20.163.232.246), port 5432 failed: server closed the connection unexpectedly\n",
      "\tThis probably means the server terminated abnormally\n",
      "\tbefore or while processing the request.\n",
      "server closed the connection unexpectedly\n",
      "\tThis probably means the server terminated abnormally\n",
      "\tbefore or while processing the request.\n",
      "\n",
      "\n",
      "During handling of the above exception, another exception occurred:\n",
      "\n",
      "Traceback (most recent call last):\n",
      "  File \"c:\\Users\\Ask78\\anaconda3\\envs\\bapi\\lib\\threading.py\", line 932, in _bootstrap_inner\n",
      "    self.run()\n",
      "  File \"c:\\Users\\Ask78\\anaconda3\\envs\\bapi\\lib\\threading.py\", line 870, in run\n",
      "    self._target(*self._args, **self._kwargs)\n",
      "  File \"C:\\Users\\Ask78\\AppData\\Local\\Temp\\ipykernel_19556\\2436743614.py\", line 57, in fetch_and_store_recent_trades\n",
      "psycopg2.InterfaceError: connection already closed\n"
     ]
    },
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "Error fetching and storing trades for joe: connection to server at \"ahsanpost.postgres.database.azure.com\" (20.163.232.246), port 5432 failed: server closed the connection unexpectedly\n",
      "\tThis probably means the server terminated abnormally\n",
      "\tbefore or while processing the request.\n",
      "server closed the connection unexpectedly\n",
      "\tThis probably means the server terminated abnormally\n",
      "\tbefore or while processing the request.\n",
      "\n",
      "Error fetching and storing trades for blz: connection to server at \"ahsanpost.postgres.database.azure.com\" (20.163.232.246), port 5432 failed: server closed the connection unexpectedly\n",
      "\tThis probably means the server terminated abnormally\n",
      "\tbefore or while processing the request.\n",
      "SSL SYSCALL error: Connection reset by peer (0x00002746/10054)\n",
      "\n"
     ]
    },
    {
     "name": "stderr",
     "output_type": "stream",
     "text": [
      "Exception in thread Thread-29:\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Users\\Ask78\\AppData\\Local\\Temp\\ipykernel_19556\\2436743614.py\", line 46, in fetch_and_store_recent_trades\n",
      "  File \"C:\\Users\\Ask78\\AppData\\Local\\Temp\\ipykernel_19556\\2436743614.py\", line 17, in get_db_connection\n",
      "  File \"c:\\Users\\Ask78\\anaconda3\\envs\\bapi\\lib\\site-packages\\psycopg2\\__init__.py\", line 122, in connect\n",
      "    conn = _connect(dsn, connection_factory=connection_factory, **kwasync)\n",
      "psycopg2.OperationalError: connection to server at \"ahsanpost.postgres.database.azure.com\" (20.163.232.246), port 5432 failed: server closed the connection unexpectedly\n",
      "\tThis probably means the server terminated abnormally\n",
      "\tbefore or while processing the request.\n",
      "SSL SYSCALL error: Connection reset by peer (0x00002746/10054)\n",
      "\n",
      "\n",
      "During handling of the above exception, another exception occurred:\n",
      "\n",
      "Traceback (most recent call last):\n",
      "  File \"c:\\Users\\Ask78\\anaconda3\\envs\\bapi\\lib\\threading.py\", line 932, in _bootstrap_inner\n",
      "    self.run()\n",
      "  File \"c:\\Users\\Ask78\\anaconda3\\envs\\bapi\\lib\\threading.py\", line 870, in run\n",
      "    self._target(*self._args, **self._kwargs)\n",
      "  File \"C:\\Users\\Ask78\\AppData\\Local\\Temp\\ipykernel_19556\\2436743614.py\", line 57, in fetch_and_store_recent_trades\n",
      "psycopg2.InterfaceError: connection already closed\n",
      "Exception in thread Thread-15:\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Users\\Ask78\\AppData\\Local\\Temp\\ipykernel_19556\\3918153311.py\", line 46, in fetch_and_store_recent_trades\n",
      "  File \"C:\\Users\\Ask78\\AppData\\Local\\Temp\\ipykernel_19556\\2436743614.py\", line 17, in get_db_connection\n",
      "  File \"c:\\Users\\Ask78\\anaconda3\\envs\\bapi\\lib\\site-packages\\psycopg2\\__init__.py\", line 122, in connect\n",
      "    conn = _connect(dsn, connection_factory=connection_factory, **kwasync)\n",
      "psycopg2.OperationalError: connection to server at \"ahsanpost.postgres.database.azure.com\" (20.163.232.246), port 5432 failed: server closed the connection unexpectedly\n",
      "\tThis probably means the server terminated abnormally\n",
      "\tbefore or while processing the request.\n",
      "server closed the connection unexpectedly\n",
      "\tThis probably means the server terminated abnormally\n",
      "\tbefore or while processing the request.\n",
      "\n",
      "\n",
      "During handling of the above exception, another exception occurred:\n",
      "\n",
      "Traceback (most recent call last):\n",
      "  File \"c:\\Users\\Ask78\\anaconda3\\envs\\bapi\\lib\\threading.py\", line 932, in _bootstrap_inner\n",
      "    self.run()\n",
      "  File \"c:\\Users\\Ask78\\anaconda3\\envs\\bapi\\lib\\threading.py\", line 870, in run\n",
      "    self._target(*self._args, **self._kwargs)\n",
      "  File \"C:\\Users\\Ask78\\AppData\\Local\\Temp\\ipykernel_19556\\3918153311.py\", line 57, in fetch_and_store_recent_trades\n",
      "psycopg2.InterfaceError: connection already closed\n"
     ]
    },
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "Error fetching and storing trades for sxp: connection to server at \"ahsanpost.postgres.database.azure.com\" (20.163.232.246), port 5432 failed: server closed the connection unexpectedly\n",
      "\tThis probably means the server terminated abnormally\n",
      "\tbefore or while processing the request.\n",
      "server closed the connection unexpectedly\n",
      "\tThis probably means the server terminated abnormally\n",
      "\tbefore or while processing the request.\n",
      "\n"
     ]
    },
    {
     "name": "stderr",
     "output_type": "stream",
     "text": [
      "Exception in thread Thread-7:\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Users\\Ask78\\AppData\\Local\\Temp\\ipykernel_19556\\3918153311.py\", line 46, in fetch_and_store_recent_trades\n",
      "  File \"C:\\Users\\Ask78\\AppData\\Local\\Temp\\ipykernel_19556\\2436743614.py\", line 17, in get_db_connection\n",
      "  File \"c:\\Users\\Ask78\\anaconda3\\envs\\bapi\\lib\\site-packages\\psycopg2\\__init__.py\", line 122, in connect\n",
      "    conn = _connect(dsn, connection_factory=connection_factory, **kwasync)\n",
      "psycopg2.OperationalError: connection to server at \"ahsanpost.postgres.database.azure.com\" (20.163.232.246), port 5432 failed: server closed the connection unexpectedly\n",
      "\tThis probably means the server terminated abnormally\n",
      "\tbefore or while processing the request.\n",
      "server closed the connection unexpectedly\n",
      "\tThis probably means the server terminated abnormally\n",
      "\tbefore or while processing the request.\n",
      "\n",
      "\n",
      "During handling of the above exception, another exception occurred:\n",
      "\n",
      "Traceback (most recent call last):\n",
      "  File \"c:\\Users\\Ask78\\anaconda3\\envs\\bapi\\lib\\threading.py\", line 932, in _bootstrap_inner\n",
      "    self.run()\n",
      "  File \"c:\\Users\\Ask78\\anaconda3\\envs\\bapi\\lib\\threading.py\", line 870, in run\n",
      "    self._target(*self._args, **self._kwargs)\n",
      "  File \"C:\\Users\\Ask78\\AppData\\Local\\Temp\\ipykernel_19556\\3918153311.py\", line 57, in fetch_and_store_recent_trades\n",
      "psycopg2.InterfaceError: connection already closed\n"
     ]
    },
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "Error fetching and storing trades for chess: connection to server at \"ahsanpost.postgres.database.azure.com\" (20.163.232.246), port 5432 failed: server closed the connection unexpectedly\n",
      "\tThis probably means the server terminated abnormally\n",
      "\tbefore or while processing the request.\n",
      "server closed the connection unexpectedly\n",
      "\tThis probably means the server terminated abnormally\n",
      "\tbefore or while processing the request.\n",
      "\n"
     ]
    },
    {
     "name": "stderr",
     "output_type": "stream",
     "text": [
      "Exception in thread Thread-19:\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Users\\Ask78\\AppData\\Local\\Temp\\ipykernel_19556\\3918153311.py\", line 46, in fetch_and_store_recent_trades\n",
      "  File \"C:\\Users\\Ask78\\AppData\\Local\\Temp\\ipykernel_19556\\2436743614.py\", line 17, in get_db_connection\n",
      "  File \"c:\\Users\\Ask78\\anaconda3\\envs\\bapi\\lib\\site-packages\\psycopg2\\__init__.py\", line 122, in connect\n",
      "    conn = _connect(dsn, connection_factory=connection_factory, **kwasync)\n",
      "psycopg2.OperationalError: connection to server at \"ahsanpost.postgres.database.azure.com\" (20.163.232.246), port 5432 failed: server closed the connection unexpectedly\n",
      "\tThis probably means the server terminated abnormally\n",
      "\tbefore or while processing the request.\n",
      "server closed the connection unexpectedly\n",
      "\tThis probably means the server terminated abnormally\n",
      "\tbefore or while processing the request.\n",
      "\n",
      "\n",
      "During handling of the above exception, another exception occurred:\n",
      "\n",
      "Traceback (most recent call last):\n",
      "  File \"c:\\Users\\Ask78\\anaconda3\\envs\\bapi\\lib\\threading.py\", line 932, in _bootstrap_inner\n",
      "    self.run()\n",
      "  File \"c:\\Users\\Ask78\\anaconda3\\envs\\bapi\\lib\\threading.py\", line 870, in run\n",
      "    self._target(*self._args, **self._kwargs)\n",
      "  File \"C:\\Users\\Ask78\\AppData\\Local\\Temp\\ipykernel_19556\\3918153311.py\", line 57, in fetch_and_store_recent_trades\n",
      "psycopg2.InterfaceError: connection already closed\n"
     ]
    },
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "Error fetching and storing trades for blz: connection to server at \"ahsanpost.postgres.database.azure.com\" (20.163.232.246), port 5432 failed: server closed the connection unexpectedly\n",
      "\tThis probably means the server terminated abnormally\n",
      "\tbefore or while processing the request.\n",
      "server closed the connection unexpectedly\n",
      "\tThis probably means the server terminated abnormally\n",
      "\tbefore or while processing the request.\n",
      "\n"
     ]
    },
    {
     "name": "stderr",
     "output_type": "stream",
     "text": [
      "Exception in thread Thread-25:\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Users\\Ask78\\AppData\\Local\\Temp\\ipykernel_19556\\2436743614.py\", line 46, in fetch_and_store_recent_trades\n",
      "  File \"C:\\Users\\Ask78\\AppData\\Local\\Temp\\ipykernel_19556\\2436743614.py\", line 17, in get_db_connection\n",
      "  File \"c:\\Users\\Ask78\\anaconda3\\envs\\bapi\\lib\\site-packages\\psycopg2\\__init__.py\", line 122, in connect\n",
      "    conn = _connect(dsn, connection_factory=connection_factory, **kwasync)\n",
      "psycopg2.OperationalError: connection to server at \"ahsanpost.postgres.database.azure.com\" (20.163.232.246), port 5432 failed: server closed the connection unexpectedly\n",
      "\tThis probably means the server terminated abnormally\n",
      "\tbefore or while processing the request.\n",
      "SSL SYSCALL error: Connection reset by peer (0x00002746/10054)\n",
      "\n",
      "\n",
      "During handling of the above exception, another exception occurred:\n",
      "\n",
      "Traceback (most recent call last):\n",
      "  File \"c:\\Users\\Ask78\\anaconda3\\envs\\bapi\\lib\\threading.py\", line 932, in _bootstrap_inner\n",
      "    self.run()\n",
      "  File \"c:\\Users\\Ask78\\anaconda3\\envs\\bapi\\lib\\threading.py\", line 870, in run\n",
      "    self._target(*self._args, **self._kwargs)\n",
      "  File \"C:\\Users\\Ask78\\AppData\\Local\\Temp\\ipykernel_19556\\2436743614.py\", line 57, in fetch_and_store_recent_trades\n",
      "psycopg2.InterfaceError: connection already closed\n"
     ]
    },
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "Error fetching and storing trades for sxp: connection to server at \"ahsanpost.postgres.database.azure.com\" (20.163.232.246), port 5432 failed: server closed the connection unexpectedly\n",
      "\tThis probably means the server terminated abnormally\n",
      "\tbefore or while processing the request.\n",
      "SSL SYSCALL error: Connection reset by peer (0x00002746/10054)\n",
      "\n"
     ]
    },
    {
     "name": "stderr",
     "output_type": "stream",
     "text": [
      "Exception in thread Thread-5:\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Users\\Ask78\\AppData\\Local\\Temp\\ipykernel_19556\\3918153311.py\", line 46, in fetch_and_store_recent_trades\n",
      "  File \"C:\\Users\\Ask78\\AppData\\Local\\Temp\\ipykernel_19556\\2436743614.py\", line 17, in get_db_connection\n",
      "  File \"c:\\Users\\Ask78\\anaconda3\\envs\\bapi\\lib\\site-packages\\psycopg2\\__init__.py\", line 122, in connect\n",
      "    conn = _connect(dsn, connection_factory=connection_factory, **kwasync)\n",
      "psycopg2.OperationalError: connection to server at \"ahsanpost.postgres.database.azure.com\" (20.163.232.246), port 5432 failed: server closed the connection unexpectedly\n",
      "\tThis probably means the server terminated abnormally\n",
      "\tbefore or while processing the request.\n",
      "SSL SYSCALL error: Connection reset by peer (0x00002746/10054)\n",
      "\n",
      "\n",
      "During handling of the above exception, another exception occurred:\n",
      "\n",
      "Traceback (most recent call last):\n",
      "  File \"c:\\Users\\Ask78\\anaconda3\\envs\\bapi\\lib\\threading.py\", line 932, in _bootstrap_inner\n",
      "    self.run()\n",
      "  File \"c:\\Users\\Ask78\\anaconda3\\envs\\bapi\\lib\\threading.py\", line 870, in run\n",
      "    self._target(*self._args, **self._kwargs)\n",
      "  File \"C:\\Users\\Ask78\\AppData\\Local\\Temp\\ipykernel_19556\\3918153311.py\", line 57, in fetch_and_store_recent_trades\n",
      "psycopg2.InterfaceError: connection already closed\n"
     ]
    },
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "Error fetching and storing trades for sxp: connection to server at \"ahsanpost.postgres.database.azure.com\" (20.163.232.246), port 5432 failed: server closed the connection unexpectedly\n",
      "\tThis probably means the server terminated abnormally\n",
      "\tbefore or while processing the request.\n",
      "SSL SYSCALL error: Connection reset by peer (0x00002746/10054)\n",
      "\n",
      "Error fetching and storing trades for chess: ('Connection aborted.', ConnectionResetError(10054, 'An existing connection was forcibly closed by the remote host', None, 10054, None))\n",
      "Error fetching and storing trades for chess: ('Connection aborted.', ConnectionResetError(10054, 'An existing connection was forcibly closed by the remote host', None, 10054, None))\n",
      "Error fetching and storing trades for chess: ('Connection aborted.', ConnectionResetError(10054, 'An existing connection was forcibly closed by the remote host', None, 10054, None))\n",
      "Error fetching and storing trades for chess: ('Connection aborted.', ConnectionResetError(10054, 'An existing connection was forcibly closed by the remote host', None, 10054, None))\n",
      "Error fetching and storing trades for perl: ('Connection aborted.', ConnectionResetError(10054, 'An existing connection was forcibly closed by the remote host', None, 10054, None))\n",
      "Error fetching and storing trades for perl: ('Connection aborted.', ConnectionResetError(10054, 'An existing connection was forcibly closed by the remote host', None, 10054, None))\n"
     ]
    }
   ],
   "source": [
    "import time\n",
    "from binance.client import Client\n",
    "import psycopg2\n",
    "from psycopg2 import sql\n",
    "import pandas as pd\n",
    "import threading\n",
    "\n",
    "# Initialize the Binance API client\n",
    "api_key = 'vijG9ARQVjevGky2bkTgFACUMmRJBVxVqwtzDIONOToNIw4YmTMxMgyy4PEVUhFH'\n",
    "api_secret = 'f9BHEpkASNW9S0nd7xe1Iq55ccd0bFrwI8LL0mA0UlIgODhubsX8noG6TnWicvmh'\n",
    "client = Client()\n",
    "\n",
    "# List of coins to fetch data for\n",
    "coins = ['sxp', 'chess', 'blz', 'joe', 'perl']\n",
    "\n",
    "def get_db_connection():\n",
    "    connection = psycopg2.connect(\n",
    "        host='ahsanpost.postgres.database.azure.com',\n",
    "        user='ahsan',\n",
    "        password='name@123',\n",
    "        dbname='postdb',\n",
    "        sslmode='require'\n",
    "    )\n",
    "    return connection\n",
    "\n",
    "# Create tables for each coin\n",
    "def create_tables():\n",
    "    connection = get_db_connection()\n",
    "    cursor = connection.cursor()\n",
    "    for coin in coins:\n",
    "        cursor.execute(sql.SQL(\"\"\"\n",
    "            CREATE TABLE IF NOT EXISTS {} (\n",
    "                id SERIAL PRIMARY KEY,\n",
    "                timestamp TIMESTAMP DEFAULT CURRENT_TIMESTAMP,\n",
    "                price NUMERIC(18, 8),\n",
    "                volume NUMERIC(18, 8)\n",
    "            )\n",
    "        \"\"\").format(sql.Identifier(f'{coin}usdt')))\n",
    "    connection.commit()\n",
    "    connection.close()\n",
    "\n",
    "def fetch_and_store_recent_trades(coin):\n",
    "    last_trade_timestamp = None\n",
    "    while True:\n",
    "        try:\n",
    "            connection = get_db_connection()\n",
    "            cursor = connection.cursor()\n",
    "            trades = client.get_recent_trades(symbol=f'{coin.upper()}USDT')\n",
    "            for trade in trades:\n",
    "                trade_timestamp = pd.to_datetime(trade['time'], unit='ms')\n",
    "                if last_trade_timestamp is None or trade_timestamp > last_trade_timestamp:\n",
    "                    cursor.execute(sql.SQL(\"INSERT INTO {} (timestamp, price, volume) VALUES (%s, %s, %s)\").format(sql.Identifier(f'{coin}usdt')), (trade_timestamp, trade['price'], trade['qty']))\n",
    "                    last_trade_timestamp = trade_timestamp\n",
    "            connection.commit()\n",
    "        except Exception as e:\n",
    "            print(f'Error fetching and storing trades for {coin}: {e}')\n",
    "            connection.rollback()\n",
    "            # Wait for 60 seconds before retrying\n",
    "            time.sleep(60)\n",
    "            continue\n",
    "        finally:\n",
    "            connection.close()\n",
    "        time.sleep(10)\n",
    "\n",
    "\n",
    "# Function to delete data older than 1 hour\n",
    "def delete_old_data(coin):\n",
    "    while True:\n",
    "        connection = get_db_connection()\n",
    "        cursor = connection.cursor()\n",
    "        try:\n",
    "            cursor.execute(sql.SQL(\"DELETE FROM {} WHERE timestamp < NOW() - INTERVAL ' HOUR'\").format(sql.Identifier(f'{coin}usdt')))\n",
    "            connection.commit()\n",
    "        except Exception as e:\n",
    "            print(f'Error deleting old data for {coin}: {e}')\n",
    "            connection.rollback()\n",
    "        finally:\n",
    "            connection.close()\n",
    "        time.sleep(3000)  # Sleep for 5 minutes\n",
    "\n",
    "# Start the threads\n",
    "def start_threads():\n",
    "    create_tables()\n",
    "    for coin in coins:\n",
    "        threading.Thread(target=fetch_and_store_recent_trades, args=(coin,)).start()\n",
    "        threading.Thread(target=delete_old_data, args=(coin,)).start()\n",
    "\n",
    "start_threads()\n",
    "\n",
    "while True:\n",
    "    time.sleep(2)\n"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "metadata": {},
   "outputs": [],
   "source": []
  }
 ],
 "metadata": {
  "kernelspec": {
   "display_name": "bapi",
   "language": "python",
   "name": "python3"
  },
  "language_info": {
   "codemirror_mode": {
    "name": "ipython",
    "version": 3
   },
   "file_extension": ".py",
   "mimetype": "text/x-python",
   "name": "python",
   "nbconvert_exporter": "python",
   "pygments_lexer": "ipython3",
   "version": "3.8.16"
  },
  "orig_nbformat": 4
 },
 "nbformat": 4,
 "nbformat_minor": 2
}
